### ISSUE TITLE
Errors when compiling

### ISSUE THREAD

**Issue by makc-ar** [marcussacana/OBJEditor#1]
Hi **marcussacana!** I have errors when compiling. 
**`public OBJHelper(byte[] Script) => Editor = new OBJ(Script);`**
Can you give an executable solution?

**Comment by marcussacana** [comment]
in the OBJHelper.cs have this line:
`public OBJHelper(byte[] Script) => Editor = new OBJ(Script);`
replace with
`public OBJHelper(byte[] Script) { Editor = new OBJ(Script); }`

Since this isn't a issue but just your compiler outdated i will not update the source.

**Comment by makc-ar** [comment]
Thanks a lot! Do you know how to edit .dat files?

**Comment by marcussacana** [comment]
https://github.com/marcussacana/Specific-Games/tree/master/Stuff's

**Comment by 0xh3LL0** [comment]
yo, its not like i cant compile this but i have similar issue about "compiling" so i'll just bump into this thread...
you know that i made [script extraction thread](https://forums.fuwanovel.net/topic/17841-script-extraction-thread/) on fuwanovel, most of them are tools from your repo...
the common question i got from them is "how can i use this?" i told them to download visual studio and compile them by their self to use it, but they wont bother to download 3gigs just to compile the tools...
i have visual studio installed but how about them? i know this is an open source, but since your tools are not "mine" i cant give them the compiled tools (i can but i wont), so thats why, i suggest you how about to add appveyor on every repo? that would be helpful, even for noob...

**Comment by marcussacana** [comment]
Ready. you can give the direct link to my appveyor, I will not link the appveyor to the readme because i'm with lazy

**Comment by 0xh3LL0** [comment]
> you can give the direct link to my appveyor

where is it?

**Comment by marcussacana** [comment]
`https://ci.appveyor.com/project/marcussacana/<reponame>`
https://ci.appveyor.com/project/marcussacana/KrKrZSceneManager
https://ci.appveyor.com/project/marcussacana/OBJEditor

If i forget of any repo, say-me

**Comment by 0xh3LL0** [comment]
Thank you very much!
